#!/bin/bash
set -e


DBNAMES=""
MYSQL_CHARSET=${MYSQL_CHARSET:-"utf8"}
MYSQL_COLLATION=${MYSQL_COLLATION:-"utf8_general_ci"}


# Checking for mysql Data directory
if [[ ! -d /var/lib/mysql//mysql ]]; then
    echo "Installing mysql database..."
    su mysql -s /bin/bash -c "mysql_install_db --datadir=/var/lib/mysql" 2>&1
fi

_ensure_mysql_running() {
    #Checking mysql is running (Thank you to Sameersbn)
    timeout=600
    while ! /usr/bin/mysqladmin -uroot status > /dev/null 2>&1
    do
        timeout=$(($timeout -1))
        if [[ $timeout -eq 0 ]]; then
            echo -e "\nCould not connect to database server. Aborting..."
            exit 1
        fi
        echo -n "."
        sleep 5
    done
}



#Creating new user and database;
echo "Starting mariadb..."
su mysql -s /bin/bash -c "/usr/bin/mysqld_safe" >/dev/null 2>&1 &

echo "Waiting for mariadb ready..."
_ensure_mysql_running

for DB_NAME in $(awk -F',' '{for (i = 1 ; i <= NF ; i++) print $i}' <<< "${DATABASES}"); do
    if [[ -n "${DB_NAME}" ]]; then
        echo "Creating database \"${DB_NAME}\"..."
        mysql -u root -e "CREATE DATABASE IF NOT EXISTS $DB_NAME DEFAULT CHARACTER SET $MYSQL_CHARSET COLLATE $MYSQL_COLLATION;"
        DB_USER_VAR="DB_USER_$DB_NAME"
        DB_USER=$DB_NAME
        if [[ -n "${!DB_USER_VAR}" ]]; then
            DB_USER=${!DB_USER_VAR}
        fi
        DB_PASS="DB_PASS_$DB_NAME"
        if [[ -n "${!DB_PASS}" ]]; then
            echo "Granting access to database \"$DB_NAME\" for user \"${DB_USER}\"..."
            mysql -u root -e "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '${DB_USER}'@'%' IDENTIFIED BY '${!DB_PASS}';"
        else
            echo "Missing DB_PASS_$DB_NAME environment variable. aborting..."
            /usr/bin/mysqladmin -u mysql shutdown
            exit
        fi
    fi
done

echo "Stopping mariadb..."
/usr/bin/mysqladmin -uroot shutdown

exec "$@"
